version: "3.8"

services:
  cache-redis:
    image: redis:latest
    container_name: cache-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - inmo-network

  inmo-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
      - mongodb
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASS=secret
      - DB_NAME=inmo
      - DB_DIALECT=mysql
      - MONGO_URI=mongodb://root:secret@mongodb:27017/logs?authSource=admin
      - JWT_SECRET=your_jwt_secret
      - AUTH0_DOMAIN=dev-ewdlkyz6st76myan.us.auth0.com
      - AUTH0_CLIENT_ID=ECtvUM0LxlcxVA1vyKJ211IepYkskgxR
      - AUTH0_CLIENT_SECRET=nGttw8E4isZdGTgpmxhssOLy9UyIfWNLAh45GFeeSsUmeySByGNGnOtP-PK7h-HD
      - AUTH0_API_TOKEN=your_auth0_api_token
    networks:
      - inmo-network

  mysql-db:
    image: mysql:latest
    container_name: mysql_inmo
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=inmo
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - inmo-network

volumes:
  redis-data:
  mysql-data:
  mongo-data:

networks:
  inmo-network:
    external: true
